# Equipe 12 - SAE 2.03
# LEVESQUE Kyliann, LE BRETON Kyllian, MENARD Esteban 
# Configuration du DockerFile

# Définition de l'image de base à savoir Debian

FROM debian:latest

# Mettre à jour les paquets et installer curl, sudo et git puis installer nodejs nécessaire pour l'utilisation de script en javascript

RUN apt update && \
	apt install -y curl sudo git && \
	curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - && \
	apt install -y nodejs

# Créer un dossier pour l'application

WORKDIR /app

# Copie le fichier de configuration package.json et le dossier courant dans le dossier précedent
COPY package*.json ./
COPY . .

# Installation des dépendances
RUN npm install

# Spécifie le port d'écoute de l'application à savoir 3000
EXPOSE 3000

# Lancement de l'application
CMD [ "npm", "start" ]